version: '3'
services:
  db:
    image: postgres
    ports:
      - '5433:5433'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    depends_on:
      - db
      - chrome
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444
volumes:
  postgresql-data:
    driver: local